version: '2'
services:
    projectone-app:
        image: projectone
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://projectone-postgresql:5432/projectone
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=projectone-elasticsearch:9300
        ports:
            - 8080:8080
    projectone-postgresql:
        extends:
            file: postgresql.yml
            service: projectone-postgresql
    projectone-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: projectone-elasticsearch
